language: go

go:
  - 1.3
  - 1.4
  - tip

before_install:
  - wget "http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.3.7-1_amd64.deb"
  - sudo dpkg -i shellcheck_0.3.7-1_amd64.deb
  - go get github.com/tools/godep
  - go get github.com/cep21/goverify
  - go get github.com/cep21/gocoverdir
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - gem install mdl

install:
  - godep go install -v .

script:
  - export PATH=$HOME/gopath/bin:$PATH
  - ./travis_check.sh
  - gocoverdir
  - goveralls -coverprofile=coverage.out -service=travis-ci

after_script:
  - cat coverage.out
